### ISSUE TITLE
WINDGAUGE03A - Tolerance rozměrů krytu

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#10]
Draft verze kapkovitého krytu se vytiskne v pořádku.

![kapkovitý kryt Draft verze](https://user-images.githubusercontent.com/1194177/56737752-6b3f8f80-676b-11e9-9dbf-1b450348eee9.jpg)

Plošný spoj pohodlně pasuje do krytu

![WINDGAUEGE03A PCB cover](https://user-images.githubusercontent.com/1194177/56737758-6f6bad00-676b-11e9-8c04-3701b417dc97.jpg)

Kapkovitý kryt, ale nejde nasadit na spodní část

![WINDGAUEGE03A not fitting cover ](https://user-images.githubusercontent.com/1194177/56737765-72669d80-676b-11e9-992c-9f149288c400.jpg)

**Comment by JanKott** [comment]
Opravil jsem přičítání parametru R03_global_clearance tak, že se přičítá jen do výřezu ve víčku, nikoliv všude kde se počítá s velikostí PCB dílů. Aktuálně to příčítá jen k šířce a výšce PCB. Hloubku jsem zatim nepřidával, protože tam nesedí plastové díly na sebe a navíc předpokládám že by dotažením šroubů mělo dojít k přitažení senzoru na tesnící kroužky.

_______________________________________________________________

commit 28204a6e2ed4a827844ff4992fe4bf1a81f965cc (HEAD -> master, origin/master, origin/HEAD)
Author: Jan Kott <jan.kott.88@gmail.com>
Date:   Thu Apr 25 20:51:42 2019 +0200

    WINDGAUGE03A #10 - Printing tolerance is now added only in the lid cut-out, not on tube platform. Lid cut-out cube size doubled.

**Comment by kaklik** [comment]
Ok, vidím, že ta oprava ovlivnila oba díly, jak R03 tak i R04.  To víčko můžu přetisknout hned, protože jeho jemnou variantu ještě vytištěnou nemám. Ale s dílem R03 asi počkám, až bude opraveno víc komplikací.

**Comment by JanKott** [comment]
R04 bude ale sedět až se přetiskne R03, protože se ve skutečnosti zmenšila plošina na R03 a R04 zůstala stejná. Mělo by to ale teď jít tisknout ve vyšší kvalitě.
Naíc budu ještě měnit R04 v rámci issue #13 kde vyměnim závity za válce.

**Comment by kaklik** [comment]
Aktuální verze krytu po přišroubování při vloženém PCB nedoléhá na spodní část modelu. Důvodem je nízká hloubka otvoru vzhledem k tloušťce PCB. Navíc při tisku dochází k "propadnutí" stropu, které dále snižuje prostor pro PCB. 
Na aktuálně vytištěném modelu je po datažení šroubů mezera pod krytem ~ 0.75mm
