### ISSUE TITLE
WINDGAUGE03A - protahování kabeláže

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#11]
Díky tomu, že vodiče jsou nerozebiratelně připevněny je slip-ringu. Tak je nutné je protahovat ze spodního otvoru dílu jak je na následující fotografii: 

![20190425_151050](https://user-images.githubusercontent.com/1194177/56738378-c3c35c80-676c-11e9-8ca1-bc116d30c149.jpg)

Někde v oblasti těsně před výstupem k PCB se ale vodiče zaseknou.  Je zde zřejmě buď nějaký ostrý záhyb, nebo nějaký úsek, který zohoršuje kvalitu vytištění trubice.

**Comment by JanKott** [comment]
Upravena ostrost záhybů průchodu pro kabeláž.

**Comment by kaklik** [comment]
Zde změna záhybů pomohla. 
Ještě by bylo užitečné vstupní část od konektoru PCB do kabelovodu v modelu lichoběžníkově rozšířit. 
Jednak by to usnadnilo protožení vodičů, protože by nebylo potřeba jednotlivé žíly lovit v otvoru u PCB  a potom by to usnadnilo vstup vodičů od konektoru do otvoru v modelu.
