### ISSUE TITLE
WINDGAUGE03A - Poloha těžiště

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#12]
K tomu, aby se anemometr mohl volně otáčet je potřeba, aby těžiště bylo přímo nad osou rotace slip-ringu.

Tak jak je naznačeno na tomto obrázku:
![anemometr_navrh](https://user-images.githubusercontent.com/1194177/51900937-c8b78080-23b6-11e9-9556-8394b3c4a804.jpg)

Aktuálně je příliš těžká zadní část s gridfiny. 

Řešením by mohlo být vytvoření kapsy na spodním okraji přední části, do které se vloží závaží. 

Potřebný rozsah závaží je přibližně vidět z této fotografie: 
![WINDGAUGE03A](https://user-images.githubusercontent.com/1194177/56739242-819b1a80-676e-11e9-9308-c9d5c3af4355.jpg)

**Comment by JanKott** [comment]
Nerozumim přesně jak si tu kapsu představuješ. Můzeš mi sem prosím přidet nějaký nákres?

**Comment by kaklik** [comment]
Ta kapsa by měla být otvor v místě toho obdélníku a měla by pokračovat dovnitř modelu. 

![20190428_182024](https://user-images.githubusercontent.com/1194177/56867446-9df4bc80-69e5-11e9-9c1c-91e9e39c61ee.jpg)

Cílem je, aby se do kapsy dala vložit takováto závaží. 

![Wolfram_noze](https://user-images.githubusercontent.com/1194177/56867475-e0b69480-69e5-11e9-8cd0-1291fbbad77b.jpg)

**Comment by JanKott** [comment]
Přidal jsem díru pro závaží. Šířka a výška se dají upravit parametry R03_balance_shelf_width a R03_balance_shelf_height. Hloubka je vždy maximální možná.

**Comment by JanKott** [comment]
Hele co mi to tu zavíráš, kam si to teď commitnu? :-P

**Comment by JanKott** [comment]
Po vyvážení rotačních částí je výsledek tento:
('Assembly COG is:', 0.0, -0.2, 197.63)
('Desired  COG is:', 0, 0, 198)

**Comment by kaklik** [comment]
Další pokračování tohoto issue zřejmě je automatické vyvážení.

**Comment by JanKott** [comment]
[https://github.com/mlab-modules/WINDGAUGE03/commit/849317cc40f68245581605f89a428111d993d3f9](url)

**Comment by JanKott** [comment]
Pro účely anemometru to, zdá se, slouží. Otázka je, jestli to má smysl dál vyvíjet kvuli jiným projektům? Pokud jsou řádově komplikovanější, tak je možné, že to vůbe použít nepůjde.

Prosím @kaklik podívej se na to a napiš jak chceš abych pokračoval.

**Comment by kaklik** [comment]
Zkoušel jsem to spustit a dostal jsem tohle: 

```
git/MLAB/WINDGAUGE03/cad$ make
# Update dependencies and make no-draft version of model in AMF.
openscad -D "draft = false" -m make -o ../amf/WINDGAUGE_S04.amf -d  ./dep/WINDGAUGE_S04.deps src/WINDGAUGE_S04.scad
# Remove absolute paths in dependencies.
sed -i "s|/media/kaklik/91d64ab1-13dc-4023-87e9-e53e8433a489/git/MLAB/WINDGAUGE03/cad/||"  ./dep/WINDGAUGE_S04.deps
# Sort deps file to keep git changes to minimum.
sort -bf  ./dep/WINDGAUGE_S04.deps -o  ./dep/WINDGAUGE_S04.deps
sed -i 's|[^\]$|& \\|'  ./dep/WINDGAUGE_S04.deps
# Add modifiers to AMF files.
./merge_modifiers.sh -v -a ../amf/WINDGAUGE_S04.amf -s src/WINDGAUGE_S04.scad
./merge_modifiers.sh: 18: ./merge_modifiers.sh: function: not found
./merge_modifiers.sh: 21: ./merge_modifiers.sh: Bad substitution
Makefile:29: recipe for target '../amf/WINDGAUGE_S04.amf' failed
make: *** [../amf/WINDGAUGE_S04.amf] Error 2
/git/MLAB/WINDGAUGE03/cad$
```

Vzhledem k tomu, že make spouštím ze stejné složky, ve které je skript 'merge_modifiers.sh', tak se mi během několika minut nepodařilo zjistit, kde je problém. 

```
$ ls -la
total 56
drwxr-xr-x 4 kaklik kaklik 4096 dub 22 00:33 .
drwxr-xr-x 7 kaklik kaklik 4096 dub 19 22:03 ..
-rw-r--r-- 1 kaklik kaklik 4039 dub 18 21:11 assembly.scad
-rw-r--r-- 1 kaklik kaklik 6931 dub 15 16:34 configuration.scad
drwxr-xr-x 2 kaklik kaklik 4096 dub 22 00:33 dep
-rwxr-xr-x 1 kaklik kaklik 9575 dub 18 21:11 get_cog.py
-rw-r--r-- 1 kaklik kaklik 2356 dub 22 00:33 Makefile
-rwxr-xr-x 1 kaklik kaklik 9347 dub 18 21:11 merge_modifiers.sh
drwxr-xr-x 3 kaklik kaklik 4096 dub 15 16:34 src
/git/MLAB/WINDGAUGE03/cad$
```

**Comment by kaklik** [comment]
Podle Yagv je otočný díl anemometru zřejmě vyvážený.  

![97574595_280059910055114_6026963409877073920_n](https://user-images.githubusercontent.com/1194177/82239940-dbeab880-9939-11ea-920f-302453e7e37f.png)


Po prozkoumání gkódu se však ukazuje, že vyvažovátko vůbec nešetří materiálem. Osa Y je tak v podstatě vyvážena modifikátorem Z.  
Ovšem díky tomu, že modifikátor Z je podstatně blíže osy rotace, tak jeho hmota musí být podstatně větší, než kdyby stejná nerovnováha byla vyvážena modifikátorem Y.

Tato skutečnost tak vede k neefektivnímu využití materiálu. 

Řešením by zřejmě bylo modifikátor Z buď zrušit, nebo vzhledem k jeho nízké účinnosti na vyvážení Z mu přidělit pouze minimální prioritu.

**Comment by kaklik** [comment]
Napadlo mě, jak zvýšit účinnost Z modifikátoru a provedl jsem úpravu jeho polohy a rozměrů.  Takto upravený modifikátor by snad neměl přispívat k vyvážení v ose Y. Tím pádem by tiskový materiál mohl být využit efektivněji.
