### ISSUE TITLE
WINDGAUGE03A - Šrouby v krytu

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#13]
V aktuálním modelu jsou dva otvory pro šrouby.  Pozice těchto otvorů je správná. 
Provedení je ale potřeba upravit tak, aby bylo možné kryt připevnit dvěma nerezovými šrouby M3x12.

To znamená vytvořit v místě označeném na fotografii kapsu, do které se po vytištění modelu z boku zasune šestihranná matice pro šroub. 

![20190425_161240](https://user-images.githubusercontent.com/1194177/56751125-97680a00-6785-11e9-8ef7-9e8d4c0a4d17.jpg)

Konstrukci kapsy lze převzít například z [tohoto modelu](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/src/666_1027.scad#L80-L84).

**Comment by JanKott** [comment]
Vyměnil jsem díry pro vruty za díry pro šrouby M3 a přidal jsem kapsy pro matice.

**Comment by JanKott** [comment]
Zapomněl jsem nahradit parametr R03_inner_screw_diameter a obalit šrouby a matice parametrem R03_global_clearance. Vzhledem k tomu, že například kapsa na matku by měla být celkem těsná, tak jsem zvětšil u šroubů a matic průměr o R03_global_clearance. Okolo PCB ale počítám R03_global_clearance z každé strany, takže konzistentní by bylo spíše přidávat R03_global_clearance k poloměru. Pokud to chceš upravit tak to na mě zas přehoď.

**Comment by kaklik** [comment]
My ty parametry průměrů šroubů a matek používáme v modelech rovnou tak jak jsou. Nepřidáváme k nim další clearance, protože by se tím zbytečně zesložiťoval kód.

**Comment by kaklik** [comment]
Šrouby do krytu pasují.
