### ISSUE TITLE
WINDGAUGE03A - Těsnění přívodů vzduchu

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#14]
Vývody vzduchu ke snímači je potřeba upravit tak, aby konec kónického tvaru obsahoval zub proti kterému se zmáčkne okroužek nasazený na snímač. 

Na snímači budou nasazené kroužky rozměru 1.5x1 mm 

![20190428_182924](https://user-images.githubusercontent.com/1194177/56867680-5d4a7280-69e8-11e9-800f-de1bb5655d10.jpg)

Tyto kroužky by měly zapadnout do zapuštění o tomto tvaru. (nakreslena jedna ze dvou trubic)

Snímač se v důsledku převrácení fotografie zasouvá ze spodní strany - do díry, která má pravoúhlé stěny. Obě díry jsou válcové.

![tube_connection](https://user-images.githubusercontent.com/1194177/56867689-879c3000-69e8-11e9-8120-a1125ceff463.jpg)

**Comment by JanKott** [comment]
Upravil jsem díry pro senzory. Díra pro senzory má teď průměr 3.5mm (parametr R03_sensor_diameter) a hloubku 2.5mm (parametr R03_sensor_depth) přechod do vzduchové trubice má 1.5mm (parametr R03_sealing_ring_thickness) a postupně se rozšiřuje na šířku vzduchové trubice (R03_air_tube_diameter).

**Comment by kaklik** [comment]
Gumové o-koužky rozmeru 1.5x1 mm doléhají a jsou stlačovány při dotažení PCB.
