### ISSUE TITLE
WINDGAUGE03A - zlepšení otáčení ve směru větru

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#15]
Současná konstrukce má velmi krátké rameno anemometru na to, aby se měřící trubice spolehlivě otáčela ve směru větru. 
Aby se tato situace zlepšila je jednak potřeba dobře vyřešit vyvážení #12  a pak také zvětšit plochu a páku směrovky, která celou trubicí otáčí. 

V tuto chvíli se zdá být jako nejlogičtější řešení zrušení gridfins a jejich nahrazení jednoduchou vertikální plochou, která se bude zasazovat do zářezu ve venturiho trubici. 
Plochá část pak může být v zářezu zajištěna dvěma šrouby podobně, jako na následujícím obrázku.
(Pohled z boku a shora)

![20190429_003145](https://user-images.githubusercontent.com/1194177/56870878-491d6a00-6a16-11e9-82a9-2aa771622e2b.jpg)

**Comment by JanKott** [comment]
Upravil jsem WINDGAUGE_R03 aby obsahoval držáky s otvory na šroub a matici a výřez pro zasunutí vertikální plochy. Vertikální plocha samotná je v souboru WINDGAUGE_R05.

**Comment by JanKott** [comment]
Opravena vzdálenost mezi dírami pro šrouby v ocasní ploše.

**Comment by kaklik** [comment]
Rozteč otvorů ve vytištěné směrovce sedí.
