### ISSUE TITLE
WINDGAUGE03A - Magnetická varianta montáže

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#16]
Nejspodnější díl nohy by bylo vhodné upravit tak, aby umožňoval montáž na střechu auta magnety zasazenými v otvorech modelu. 

Magnety by měly být tři symetricky na okolo středu. Do vytištěného modelu se budou vkládat z vrchní strany. Aby mezi kovovou střechou a magnetem bylo několik vytištěných vstev.  Vytištěné vrstvy by měly snížit riziko pošklábání laku kovovými díly.

**Comment by ChroustJan** [comment]
@kaklik  bylo by dobré počítat s tím, že mezi střechu a tištěný díl bude muset přijít nějaká látka (filc). Ty laky se strašně snadno poškrábou.

**Comment by kaklik** [comment]
V takovém případě je možná dobré tam spíš použít magnet se šroubem. 
https://www.unimagnet.cz/659-HS-13-magneticky-uchyt.html

Důsledkem bude, že magnet bude mít lépe uzavřené magnetické pole. Ale zas může být našroubovaný zespodu. Takže mezi střechou a magnetem bude jen vrstva filcu.

**Comment by ChroustJan** [comment]
To by bylo dobré. Ideální by bylo, kdyby ten magnet měl průměr jako samolepící filc pod židle:
https://www.hornbach.cz/shop/Plstena-podlozka-pod-nabytek-Tesa-samolepici-16x/7653785/artikl.html?wt_cc2=39707792591&wt_cc3=162907844153&gclid=Cj0KCQjw5J_mBRDVARIsAGqGLZAA_16JfdoLR9tXLOQK_wRNeZmZ4r1SoIaEqdLWSCzNK0W_rfcl4qIaAtO8EALw_wcB&wt_cc6=7653785&wt_mc=cz.paid.sea.google.alwayson_assortment..zzpla_kategorie_desktop.697261189.39707792591.&wt_cc1=697261189

**Comment by kaklik** [comment]
@ChroustJan  Tohle má úplně zanedbatelný průměr.  Filcovou podložku budeme muset vystřihnout, protože by zřejmě měla být přes celou plochu toho spodního držáku. Tedy přes celou spodní stranu tohoto dílu: 
https://github.com/MLAB-project/Modules/blob/master/mechanical/WINDGAUGE03A/amf/P_WINDGAUGE03A_D02.stl

**Comment by kaklik** [comment]
[Magnetické úhychy M5](https://www.unimagnet.cz/659-HS-13-magneticky-uchyt.html) by měly být v trojúhelníku okolo středového šroubu (který se bude do dílu montovat pouze v případě fixního uchycení, nebo uchycení na nemagnetický materiál). 

Středový šroub M6 by měl mít šestihranné zapuštění pro hlavu, aby jej při dotahování nebylo potřeba džet klíčem. 

Matice M5 šroubů od magnetů by měly být taktéž částečně zapuštěny.  Magnety ze spodní strany budou zapuštěny úplně a do modelu se zašroubují tak, že budou namagnetovány na tyčku, nebo hlavu roubu, se kterou se bude otáček pro dotažení do zapuštěné matice. 

Výsledné konstrukční řešení je zachyceno na následujícím obrázku: 

![20190505_001826](https://user-images.githubusercontent.com/1194177/57185470-8b3e2400-6ecc-11e9-9694-37dc2bbd418e.jpg)

**Comment by JanKott** [comment]
1) Jsem přepsal názvy proměnných do angličtiny a trochu jsem upravil odsazení v kódu. Původní proměnné jsem v souboru configuration.scad zachoval s odkazem na nové, kvůli případné kompatibilitě.
2) Zapuštění středové matice jsem přesunul na opačnou (vnitřní) stranu základny.
3) Přidal jsem díry na magnety HS-13 M5 na spodní část s extra rezervou 1.5 x D02_global_clearance kvůli tisku do vzduchu + díry na šroub M5 a kapsy pro zapuštění matek (do půlky jejich výšky) do vnitřní strany základny.

**Comment by kaklik** [comment]
![20190507_150853_crop](https://user-images.githubusercontent.com/1194177/57304591-e5630300-70df-11e9-85a6-724b7924629b.jpg)

Ve vytitštěném dílu nevychází tolerance otvoru pro magnet a magnet tam nejde zasunout. 

Otvor pro magnet by se hodilo překrýt jednou tištěnou vrstvou materiálu, která se pak po vytištění modelu propíchne. Podstatně to zlepší kvalitu výtisku.  K tomuto účelu je využíván [tento parametr](https://github.com/ThunderFly-aerospace/TF-R1/blob/c42b452ed2c369f34fbee3830a4b5310c39054a7/CAD/parameters.scad#L8).

**Comment by kaklik** [comment]
Asi by taktéž bylo zlepšení, kdyby magnety byly umístěny na větším poloměru.  Podstavec by pak byl stabilnější.

**Comment by JanKott** [comment]
Přidal jsem toleranci global_clearance k průměru základny magnetu. Přidal jsem tenkou vrstvu layer_thickness nad základnu magnetu pro zlepšení tisku. Díry na magnet jsem dal co nejblíže k okraji základny tak, aby tam stále šly umístit matky shora.

**Comment by kaklik** [comment]
Tolerance otvorů i rozmístění magnetů nyní vyhovuje.
