### ISSUE TITLE
Schéma k I2CADC02A nenajde knihovny

### ISSUE THREAD

**Issue by povik** [MLAB-project/Modules#20]
![Screenshot from 2019-08-16 20-25-22](https://user-images.githubusercontent.com/382160/63189394-316cfe80-c064-11e9-9964-ddf0b405aff1.png)

**Comment by kaklik** [comment]
Tohle ale není problém jen tohoto schéma ale celého způsobu se zacházením KiCADu s knihovnami. 
Ten projekt by bylo potřeba přeuložit s novými knihovnami, aby to zas fungovalo.
