### ISSUE TITLE
PROGLOG01A

### ISSUE THREAD

**Issue by povik** [MLAB-project/Modules#22]
PROGLOG01A by měl být modul malého hradlového pole ICE40UP5K od Lattice. Pozoruhodné na tomto poli je, že lze programovat open-source nástroji.

**Comment by povik** [comment]
Ve schématu je třeba ještě alespoň

- určit velikost flash paměti
- zajistit hranu na RESET pinu po připojení napájení, a asi přidat resetovací tlačítko
- rozmyslet zapojení programovacího hřebínku
- zajistit nástup napájení ve správném pořadí

K poslednímu mám otázku: Čím spínat 3V3 napájení, které je z vnější přivedeno k modulu a které má na hradlovém poli nastoupit až po regulovaných 1V2? Jak zajistit minimální úbytek?

**Comment by kaklik** [comment]
Možná by ti mohlo pomoci řešení [tohoto modulu](https://github.com/MLAB-project/Modules/blob/master/power_supply/BATPOWER05A/hw/sch_pcb/BATPOWER05A.pdf) který kreslil @ChroustJan. 

Další možnost jsou [power sequencers](http://www.ti.com/power-management/sequencers/overview.html#), nebo [powerpath controllers](https://www.analog.com/en/products/monitor-control-protection/powerpath-ideal-diodes-load-switches.html#)

**Comment by kaklik** [comment]
Tohle mi přijde jako již vyřešené.
