### ISSUE TITLE
WINDGAUGE03A - tloušťka trubice pro kabely

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#28]
Během  testování anemometru se ukázalo, že tlakový snímač se saturuje již při ryclostech proudění okolo 80km/h. S cílem tuto rychlost zvětšit jsem zvětšil průměr zúžené části. 

To bylo snadné, protože průměr trubice pro kabely se od tohoto průměru odvozuje. Takže přepočet zafungoval a vznikl nový vytisknutelný model s nekřížícími se trubicemi. 

![image](https://user-images.githubusercontent.com/1194177/76642245-270bd800-6553-11ea-8322-d5ce00eda6d5.png)

Model jsem vytiskl a při montáži ložiska jsem zjistil, že novým průměrem trubice pro kabely neprocpu vodiče, protože je moc malý. 
Pokusil jsem se vypátrat příčinu a zjistil jsem při tom, že výpočet průměru trubice pro vodiče je hodně pesimistický a lze z jeho náraků ubrat. Zvýšil jsem tak průměr kabelové trubice ale nyní v důsledku zvetšení průměru užší části koliduje s tlakovým kanálkem, který do této části vede. 

![image](https://user-images.githubusercontent.com/1194177/76641914-9e8d3780-6552-11ea-942e-2c2274720a6c.png)

Řešení zřejmě je kanálek s vodiči přivézt do protostoru konektoru PCB zboku, nikoliv ze zadní strany. Tato úprava je ale už trochu náročnější protože vyžaduje ubrat koleno na konci kanálku s vodiči a celý kanálek zřejmě nějak asymetricky posunout. 

Výsledkem by mělo být že tlakokový kanálek povede přímo do zůženého místa a kanálek s vodiči ho nebude křižovat a do prostoru konektoru se bude napojovat z boční strany.

**Comment by kaklik** [comment]
Nákres ideového návrhu řešení změny kanálku

![Screenshot from 2020-03-21 18-04-47](https://user-images.githubusercontent.com/1194177/77232196-d96d1c00-6b9f-11ea-9887-7bbde3ddcf68.gif)

Červenou šipkou je označeno nové místo vstupu kanálku vodičů pod konektor PCB. 
Modrou šipkou je označena rotace šikmé části přívodního kanálku. 

**Při úpravách je nutné zachovat vyvýšenost lemu pod PCB vůči obrysu kapky ze všech stran. Aby voda nemohla volně téct skulinou mezi trubicí a kapkovitým krytem do kanálku vodičů.**

**Comment by JanKott** [comment]
Po úpravě to tedy vypadá takto:

![68747470733a2f2f66696c65732e6769747465722e696d2f4a616e4b6f74742f384e795a2f7468756d622f536e696d656b2d6f6272617a6f766b792d323032302d30332d32322d762d31392e35302e31382e706e67](https://user-images.githubusercontent.com/24248720/77349201-f0944100-6d3a-11ea-9362-3129739945b2.png)
