### ISSUE TITLE
LIGHTNING01A

### ISSUE THREAD

**Issue by ChroustJan** [MLAB-project/Modules#3]
@roman-dvorak 
- Pomoci 0R umoznit nezapojit vnitrni stabilizator (odebírá to jen 1/10 toho co se stabilizatorem, dulezite pro baterkova reseni)
- Dát na vstupni napajeni C 47uF pouzdro C (bylo by dobré kdyby se povedlo C 100nF dát blíž IO, vypadá to že nějaké místo tam je)
- Opravit adresy na potisku modulu. Korektní adresy jsou: [0x02, 0x01, 0x03].

**Comment by kaklik** [comment]
Tohle je ještě pořád aktivní issue? Myslel jsem, že ten modul už je v produkci.

**Comment by kakl** [comment]
Neni to vyreseno

Dne čt 13. 9. 2018 14:59 uživatel Jakub Kákona <notifications@github.com>
napsal:
