### ISSUE TITLE
GPS01C - revize

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#33]
@ChroustJan  Prohlížel jsem si nově navržený modul [GPS01C](https://github.com/MLAB-project/Modules/tree/master/sensors/GPS01C) určený pro RTK navigaci. 

Nerozumím několika záležitostem: 

1. Jak má fungovat toto zapojení: 
![image](https://user-images.githubusercontent.com/1194177/83202291-956e3880-a147-11ea-9835-b0106e38ac8b.png)
Přijde mi, že zenerova dioda tam nemá prakticky žádnou jinou funkci než, jako standardní dioda, která zabraňuje tomu, aby se kondenzátor vybil do napájení +3V3.

1. V téhle části se mi zdá, že je tam jeden z napájecích konektorů navíc: 
![image](https://user-images.githubusercontent.com/1194177/83202581-26ddaa80-a148-11ea-92a9-d63674d5045c.png)
Není mi zároveň jasná funkce přepínacího jumperu napájení. Očekával bych, že modul je buď napájen z USB, nebo z externího zdroje. Myslím že nedává smysl, aby byl napájen z externího zdroje a zároveň připojen na USB. Předchozí modul GPS01B rozlišoval stav, napájeno z USB a vypnuto USB na tomto modulu nevidím žádný snímací pin, který by to umožňoval rozlišit. 
Pokud ale ubrání jednoho hřebínku nevede ke zmenšení, nebo zjednodušený modulu, tak to asi není potřebné řešit. 

Neměl by se modul jmenovat spíše GPS02A? Když používá dost jinou řadu uBlox čipů?

**Comment by ChroustJan** [comment]
1. Chápeš to dobře. Vzal jsem to z předchozího modulu. Podle mě jsme jí tam dali kvůli tomu že jí máme skladem a měla možná menší úbytek než M4 a byla menší.

2. Modul umí odpojit USB. Je to hřebínkem USBON na PCB. Já to v zásadě udělal zas jak u předchozí verze. A je možné že to nikdy nevyužíváme a je to zbytečné. Nevím zda může nastat stav, že by jsme měli zastrčené USB a chtěli to napájet z hřebínku.

U názvu jsem vycházel z toho, že je to náhrada předchozího.

**Comment by roman-dvorak** [comment]
> Myslím že nedává smysl, aby byl napájen z externího zdroje a zároveň připojen na USB.

Tak tohle si úplně nemyslím. Protože třeba při posledním testu jsme zpozorovali, že je možné, že nějaké USB zařízení bylo odpojeno kvůli napájení. Byl tam asi problém, že zřejmě modem bere více než o sobě říká. Ale tento problém by šlo také vyřešit tím, že do GPS by se přivedlo externí napájení a USB by fungovalo.

**Comment by kaklik** [comment]
> > Myslím že nedává smysl, aby byl napájen z externího zdroje a zároveň připojen na USB.
> 
> Tak tohle si úplně nemyslím. Protože třeba při posledním testu jsme zpozorovali, že je možné, že nějaké USB zařízení bylo odpojeno kvůli napájení. Byl tam asi problém, že zřejmě modem bere více než o sobě říká. Ale tento problém by šlo také vyřešit tím, že do GPS by se přivedlo externí napájení a USB by fungovalo.

Ano, ale USB nemůže fungovat dobře, pokud tam existují zařízení, která si říkají o nepravdivý odběr. 
Takže tohle je potřeba řešit na úrovni modemu, nikoliv externím napájením jiných zařízení.  Tohle je velmi specifický případ a neměl by nastávat.

**Comment by kaklik** [comment]
>     1. Chápeš to dobře. Vzal jsem to z předchozího modulu. Podle mě jsme jí tam dali kvůli tomu že jí máme skladem a měla možná menší úbytek než M4 a byla menší.

Z hlediska napěťového úbytku je tam myslím vhodné zvolit nějakou shottkyho diodu. 
Třeba tohle vypadá použitelně: https://www.vishay.com/docs/85510/bas85.pdf (pokud nevadí to kulatý pouzdro)

> 
>     2. Modul umí odpojit USB. Je to hřebínkem USBON na PCB. Já to v zásadě udělal zas jak u předchozí verze. A je možné že to nikdy nevyužíváme a je to zbytečné. Nevím zda může nastat stav, že by jsme měli zastrčené USB a chtěli to napájet z hřebínku.

Já si myslím, že by taková situace neměla nastat.  Záležitost, kterou zmiňuje Roman musíme vyřešit na modemu, nikoliv na GPS. 

> 
> 
> U názvu jsem vycházel z toho, že je to náhrada předchozího.

Náhrada to je, ale není to oprava návrhu, je to funkčně jiný modul. Z toho důvodu se má změnit to číslo, nikoliv písmeno.

**Comment by ChroustJan** [comment]
Přejmenoval jsem modul na 02A. Provedu ještě nějaké kontroly, ale jinak je modul ve výrobním stavu.
