### ISSUE TITLE
Držák kabelů k desce ALBASE 

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#8]
Je potřeba tištěný díl pro uchycení kabelů různých průměrů na desce ALBASE.  Jeho účelem je umožňit připojení tlustých špatně ohebných kabelů k modulům MLAB. 

Typické využití takového vývodu je u měřících stanic této konstrukce: 

![20190409_115541](https://user-images.githubusercontent.com/1194177/55791419-bcd6f180-5abe-11e9-9c53-b6c7fd2da784.jpg)

Kde vlevé části obrázku vede tlustý kabel s průměrem 10mm, který by měl být přichycený k základní desce před tím, než bude připojen k modulu. 

Konstrukce držáku může vycházet z [existujícího modelu](https://github.com/ThunderFly-aerospace/TF-R1/blob/master/CAD/src/cable_clamp.scad) pro uchycení kabelů ke startovací desce. 
Využití tohoto modelu je výhodné, neboť již řeší parametričnost počtu kabelů a jejich průměrů.

![image](https://user-images.githubusercontent.com/1194177/55790070-e8a4a800-5abb-11e9-9c74-7423a2a88610.png)

Je pouze nutné tento úchyt upravit tak, aby jej bylo možné přišroubovat na tento okraj [modulární desky ALBASE](https://github.com/MLAB-project/Modules/blob/master/mechanical/ALBASE1521/hw/cam_ama/ALBASE1521.pdf):

![Screenshot from 2019-04-09 11-42-27](https://user-images.githubusercontent.com/1194177/55790491-be071f00-5abc-11e9-8a93-70ecd9feed5c.png)

Model by měl být umístěn ve složce desky, ke které má pasovat. 
https://github.com/MLAB-project/Modules/tree/master/mechanical/ALBASE1521/hw

**Comment by roman-dvorak** [comment]
Držák by měl fungovat tak, že se definuje vzdálenost a průměr připevňovacích šrubů. 

Jednotlivé vodiče budou definovány polem, který bude obsahovat pole s průměry jednotlivých vodičů. Skupina vodičů bude následně pod jedním protikusem přidělaným pomocí dvou šroubů ve správném rastru. 

Definice pak bude moct vypadat následovně:
```
wires = [[10, 10, 10, 5]];   // 4 vodiče pod jedním protikusem
wires = [[10, 10], [5, 4, 4]]; // 2 protikusy. První bude držet dvojici 10 mm kabelů. Další bude mít 3 tečí kabely
wires = [[10], [5], [5], [3]]; // 4 kabely. Každý bude samostatně připevněný.
```

Vygenerovaný STL soubor musí obsahovat základní díl, tak i všechny příchytky vedle sebe. Tak, aby to bylo možné vytisknout vše najednou. 

Příchytky musí být možné generovat samostatně - to samé platí o základním dílu.

**Comment by JakubMares96** [comment]
Ahoj, mám dotaz, jaké šrouby se použijí pro připojování jednotlivých kabelových modulů? Budou to šrouby M3 se šestihrannou hlavou a čtvercovou matičkou? Pro připojení k desce ALBASE bude M3 s válcovou hlavou a šestihrannou matkou?

Zde je pracovní verze s těmito parametry wires =  [[2,8,5],[5,20],[10,10]];
![image](https://user-images.githubusercontent.com/48317171/60337957-c167c380-99a4-11e9-8179-739e4575255a.png)

**Comment by kaklik** [comment]
Mě přijde rozumné tam všude používat stený typ šroubů tj. M3  DIN 912 - válcová inbus hlava.

**Comment by JakubMares96** [comment]
@kaklik @ChroustJan 
Zde je nejaktuálnější podoba. 
![image](https://user-images.githubusercontent.com/48317171/60427914-046da500-9bf8-11e9-9a21-55cd8067b454.png)

![image](https://user-images.githubusercontent.com/48317171/60427925-0d5e7680-9bf8-11e9-976b-6a7e62307e34.png)
