### ISSUE TITLE
Distanční sloupek pro desku ALBASE

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/Modules#9]
V některých aplikacích je vhodná montáž více desek ALBASE nad sebe. 
Příkladem jsou [detekční stanice sítě Bolidozor](https://github.com/bolidozor/RMDS).

V současné době jsou desky spojovány použitím závitových tyčí M5 řezaných na délku 120mm. 
Každá deska je pak na závitovou tyč uchycena dvojicí matic a podložek. 
Toto řešení je však výrobně nepraktické, neboť vyžaduje precizní začištění každého řezu závitové tyče, aby bylo možné matici na závit nasadit. 

Zlepšením může být použití 3D tištěného sloupku. Do kterého se vloží klasické šestihranné matice M5 a desky se připevní šrouby. 

Podoba sloupku by zřejmě měla, taková jak je na následujícím obrázku. 

![20190409_143850](https://user-images.githubusercontent.com/1194177/55802220-10a20480-5ad8-11e9-81c7-fbc03e6b9ab3.jpg)

Zde je šestihranný sloupek, který má průměr na 13 klíč pro podržení při šroubování.  Uprostřed sloupku je šestihranná dutina, která je symetricky na dvou stranách otevřena. 
Sloupek je konstruován tak, aby umožnil tisk jak na stojato, tak i při položení na otevřenou stranu ještiúhelníku. 

Pro tisk na stojato jsou konce do kterých pasují matky opatřeny šikmým náběhem, aby nedocházelo k tisku vodorovného převisu. Strop kapsy na matku je navíc zaslepen jednou vrstvou materiálu, aby před tiskem díry byl nejdřív otvor pro matku zaslepen mostem.
Jedna vrstva materiálu v díře pro šroub se propíche šroubem během montáže. 

Otvor na matici musí být mírně kónický, aby matice neměla tendenci vypadnout při vyšroubování šroubu. 

Délka sloupku bude hlavním parametrem modelu.

**Comment by ChroustJan** [comment]
@kaklik neměla by ta kapsa na matku být z boku? Tak jak to děláme u krabiček? Podle mě se tam bude pěkně blbě vkládat a bude nám vypadávat při montáži. Případně je to potřeba více rozkreslit. Není to úplně jasné:(

**Comment by JakubMares96** [comment]
Po schůzce s @kaklik jsem udělal návrh distančního sloupku #9, viz:
![distance_leg_preview_2](https://user-images.githubusercontent.com/48317171/58506012-a1b76280-818e-11e9-8f83-b2aa3d6efbbe.PNG)
![distance_leg_preview_1](https://user-images.githubusercontent.com/48317171/58506020-a3812600-818e-11e9-8ad4-d50fb40bfc73.PNG)
![distance_leg_layout](https://user-images.githubusercontent.com/48317171/58506025-a54ae980-818e-11e9-85b9-21d375450ec4.PNG)
Mohl bych poprosit o radu kam a pod jakým názvem to nahrát na git?
Prosím o názor a připomínky.

**Comment by kaklik** [comment]
Patří to do [tohoto souboru](https://github.com/MLAB-project/Modules/blob/master/mechanical/ALBASE1521/cad/src/888_1001.scad). 

Kóty se dají vytvářet i v modelech openscadu, je zbytečné kreslit nákres v jiném nástroji. http://www.cannymachines.com/entries/9/openscad_dimensioned_drawings

**Comment by kaklik** [comment]
Taky by se hodilo odebrat zbytečný materiál ve vnitřní části sloupku.  Zde může být odečten klidně šestihran odpovídající minimálně průměru matice. 
Prosté odečtení ale způsobí že matice bude bez šroubu zapadávat do sloupku, což je nežádoucí stav.

**Comment by kaklik** [comment]
Vyřešeno hliníkovými distančními sloupky. 

![248375098_597448768361027_1175605899832408471_n](https://user-images.githubusercontent.com/1194177/141455975-8b98c8a2-4476-4403-920d-8f68f1462fc7.jpg)
